(() => {
  'use strict';
  const STORAGE_KEY='kitchenos-v5.2-state'; const MODE_KEY='kitchenos-v5.2-mode';
  const todayKey=()=>new Date().toISOString().slice(0,10);
  const defaults={
    modules:{kitchen:[
      {id:'temperature',name:'Temperature',symbol:'°',description:'Opening, closing and checks',enabled:true},
      {id:'cleaning',name:'Cleaning',symbol:'✦',description:'Daily and scheduled cleaning',enabled:true,status:'1 late',late:true},
      {id:'deliveries',name:'Deliveries',symbol:'↓',description:'Receive and verify goods',enabled:true,status:'Create report'},
      {id:'cooking',name:'Cooking',symbol:'◒',description:'Cooking temperature records',enabled:true,status:'Ready'},
      {id:'cooling',name:'Cooling',symbol:'❄',description:'Cooling and blast-chill records',enabled:true,status:'Ready'},
      {id:'prep',name:'Prep List',symbol:'≡',description:'What needs preparing today',enabled:true,status:'6 items'},
      {id:'maintenance',name:'Maintenance',symbol:'◇',description:'Report an operational issue',enabled:true,status:'1 open'},
      {id:'handover',name:'Handover',symbol:'↗',description:'Only relevant shift information',enabled:true,status:'New'}],
      service:[{id:'opening',name:'Opening',symbol:'↗',description:'Opening checklist',enabled:true,status:'1 open'},{id:'cleaning',name:'Cleaning',symbol:'✦',description:'Daily and scheduled cleaning',enabled:true,status:'Ready'},{id:'temperature',name:'Temperature',symbol:'°',description:'Display and service fridges',enabled:true,status:'Ready'},{id:'closing',name:'Closing',symbol:'↘',description:'Closing checklist',enabled:true,status:'Later'},{id:'handover',name:'Handover',symbol:'↗',description:'Relevant shift information',enabled:true,status:'New'},{id:'maintenance',name:'Maintenance',symbol:'◇',description:'Report an operational issue',enabled:true,status:'Ready'}]},
    assets:[
      {id:'fridge-1',name:'Fridge 1',type:'fridge',min:0,max:5,step:.1,default:4},
      {id:'fridge-2',name:'Fridge 2',type:'fridge',min:0,max:5,step:.1,default:4},
      {id:'freezer-1',name:'Freezer 1',type:'freezer',min:-24,max:-18,step:.1,default:-18},
      {id:'blast-chiller',name:'Blast Chiller',type:'fridge',min:0,max:5,step:.1,default:3},
      {id:'hot-holding',name:'Hot Holding',type:'hot',min:63,max:90,step:.5,default:65}
    ],
    cleaningTasks:[
      {id:'hood',title:'Extraction hood surfaces',area:'Kitchen · Hot line',instructions:'Degrease all accessible hood surfaces, wipe dry and check that no residue remains.',bucket:'today',due:'14:00'},
      {id:'prep-benches',title:'Prep benches and undershelves',area:'Kitchen · Preparation',instructions:'Remove equipment, clean and sanitise the full worktop and all undershelf contact points.',bucket:'today',due:'16:00'},
      {id:'walk-in-floor',title:'Walk-in fridge floor',area:'Kitchen · Cold storage',instructions:'Sweep, wash and sanitise the floor. Keep all food raised and protected during cleaning.',bucket:'today',due:'18:00'},
      {id:'oven-deep-clean',title:'Combi oven deep clean',area:'Kitchen · Hot line',instructions:'Run the approved deep-clean cycle, wipe seals and confirm the chamber is free from residue.',bucket:'overdue',due:'Yesterday'},
      {id:'dry-store-racks',title:'Dry-store lower racks',area:'Kitchen · Dry store',instructions:'Remove stock from the lower level, clean the racks and floor edges, then replace stock safely.',bucket:'overdue',due:'2 days late'}
    ],
    staff:['Francesco','Rubens','Maria','Luca','Sofia'], cleaningRecords:{}, auditLog:[], records:{}
  };
  const clone=x=>JSON.parse(JSON.stringify(x));
  function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(s?.modules?.kitchen&&s?.assets)return s}catch{}return clone(defaults)}
  let state=load(); state.issues??={}; state.cleaningTasks??=clone(defaults.cleaningTasks); state.staff??=clone(defaults.staff); state.cleaningRecords??={}; state.auditLog??=[]; let mode=localStorage.getItem(MODE_KEY)||'manager'; let session='opening'; let currentIndex=0; let draftValue=0; let draftNote=''; let touchStartX=0; let wheelTouchStartY=0; let wheelLastY=0; let wheelAccumulator=0; let selectedAction=''; let pendingSaveNext=true; let currentCleaningId=''; let signatureHasInk=false; let signatureDrawing=false;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
  const escapeHtml=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  const recordBucket=()=>{const d=todayKey(); state.records[d]??={opening:{},closing:{}}; return state.records[d][session]};
  const assetIcon=t=>t==='freezer'?'❄':t==='hot'?'♨':'▣';
  function statusFor(asset,value){if(value<asset.min||value>asset.max)return{label:'Action required',className:'high'};return{label:'Within range',className:'ok'}}
  function showPage(name){$$('[data-page]').forEach(p=>p.classList.toggle('active',p.dataset.page===name));$$('[data-target]').forEach(b=>b.classList.toggle('active',b.dataset.target===name));}
  function setMode(next){mode=next;localStorage.setItem(MODE_KEY,mode);$('#appShell').dataset.mode=mode;$('#modeChipLabel').textContent=`${mode[0].toUpperCase()+mode.slice(1)} preview`;$('#workspaceSubtitle').textContent=mode==='manager'?'Manager control centre':`${mode[0].toUpperCase()+mode.slice(1)} workspace`;$('#modeMenu').classList.remove('open');showPage(mode==='manager'?'dashboard':mode)}
  const cleaningBucket=()=>{const d=todayKey();state.cleaningRecords[d]??={};return state.cleaningRecords[d]};
  const openCleaningTasks=()=>state.cleaningTasks.filter(t=>!cleaningBucket()[t.id]);
  function addAudit(module,action,entityId,details={}){state.auditLog.push({id:`audit-${Date.now()}-${Math.random().toString(16).slice(2)}`,module,action,entityId,details,at:new Date().toISOString()});if(state.auditLog.length>300)state.auditLog=state.auditLog.slice(-300)}
  function syncCleaningIssues(){const d=todayKey();state.issues[d]??={};state.cleaningTasks.filter(t=>t.bucket==='overdue').forEach(t=>{const key=`cleaning-${t.id}`;if(cleaningBucket()[t.id]){if(state.issues[d][key])state.issues[d][key].status='resolved'}else state.issues[d][key]={source:'cleaning',taskId:t.id,title:t.title,action:'complete-cleaning',status:'open',createdAt:state.issues[d][key]?.createdAt||new Date().toISOString()}})}
  function cleaningStatusText(){const total=state.cleaningTasks.length,done=Object.keys(cleaningBucket()).length,overdue=openCleaningTasks().filter(t=>t.bucket==='overdue').length;return overdue?`${overdue} overdue`:done===total?'Complete':`${total-done} open`}
  function temperatureStatusText(){const total=state.assets.length;const done=Object.keys(state.records[todayKey()]?.opening||{}).length;return done===total?'Complete':`${total-done} open`}
  function renderModules(dep){const c=$(`#${dep}Modules`);c.innerHTML=state.modules[dep].filter(x=>x.enabled).map(x=>{let status=x.status||'Ready';if(x.id==='temperature'&&dep==='kitchen')status=temperatureStatusText();if(x.id==='cleaning')status=cleaningStatusText();return`<button class="module-card" data-open-module="${dep}" data-module-id="${escapeHtml(x.id)}"><span class="module-status ${x.late?'late':''}">${escapeHtml(status)}</span><span class="module-symbol">${escapeHtml(x.symbol)}</span><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.description)}</small></button>`}).join('');c.querySelectorAll('[data-open-module]').forEach(b=>b.onclick=()=>openModule(dep,b.dataset.moduleId))}
  function openModule(dep,id){if(id==='cleaning'){renderCleaningList();showPage('cleaning-list');return}if(id==='temperature'&&dep==='kitchen'){session='opening';renderTemperatureList();showPage('temperature-list');return}const item=state.modules[dep].find(x=>x.id===id);$('#modalSymbol').textContent=item?.symbol||'+';$('#modalEyebrow').textContent=`${dep} workflow`;$('#modalTitle').textContent=item?.name||'Module';$('#modalDescription').textContent='This workflow will be built in the next sprint.';openModal($('#moduleModal'))}
  function renderEditors(){['kitchen','service'].forEach(dep=>{const c=$(`#${dep}Editor`);c.innerHTML=state.modules[dep].map((x,i)=>`<div class="module-toggle-row"><span class="mini-symbol">${escapeHtml(x.symbol)}</span><span><strong>${escapeHtml(x.name)}</strong><small>Position ${i+1}</small></span><label class="switch"><input type="checkbox" data-toggle="${dep}" data-id="${escapeHtml(x.id)}" ${x.enabled?'checked':''}></label></div>`).join('');c.querySelectorAll('[data-toggle]').forEach(i=>i.onchange=()=>{const x=state.modules[i.dataset.toggle].find(v=>v.id===i.dataset.id);x.enabled=i.checked;save();renderModules(i.dataset.toggle);toast(`${x.name} ${i.checked?'shown':'hidden'}`)})})}
  function renderTemperatureEditor(){const c=$('#temperatureEditor');c.innerHTML=state.assets.map((a,i)=>`<div class="asset-editor-row" data-asset-row="${a.id}"><input data-field="name" value="${escapeHtml(a.name)}" aria-label="Equipment name"><select data-field="type"><option value="fridge" ${a.type==='fridge'?'selected':''}>Fridge</option><option value="freezer" ${a.type==='freezer'?'selected':''}>Freezer</option><option value="hot" ${a.type==='hot'?'selected':''}>Hot holding</option></select><input type="number" step="0.1" data-field="min" value="${a.min}" aria-label="Minimum"><input type="number" step="0.1" data-field="max" value="${a.max}" aria-label="Maximum"><button data-delete-asset="${a.id}">Delete</button></div>`).join('');c.querySelectorAll('[data-asset-row]').forEach(row=>row.querySelectorAll('[data-field]').forEach(input=>input.onchange=()=>{const a=state.assets.find(x=>x.id===row.dataset.assetRow);const f=input.dataset.field;a[f]=['min','max'].includes(f)?Number(input.value):input.value;save();renderTemperatureList();toast('Temperature setup saved')}));c.querySelectorAll('[data-delete-asset]').forEach(b=>b.onclick=()=>{if(state.assets.length<=1)return toast('Keep at least one equipment item');state.assets=state.assets.filter(a=>a.id!==b.dataset.deleteAsset);save();renderTemperatureEditor();renderTemperatureList();renderModules('kitchen')})}
  function renderTemperatureList(){const rec=recordBucket();const total=state.assets.length;const done=Object.keys(rec).length;$('#temperatureOpenBadge').textContent=done===total?'Complete':`${total-done} open`;$('#temperatureAssetList').innerHTML=state.assets.map((a,i)=>{const r=rec[a.id];const s=r?statusFor(a,r.value):{label:'Pending',className:'pending'};return`<button class="temperature-row" data-temp-asset="${i}"><span class="progress-circle ${r?'done':''}">${r?'✓':''}</span><span><strong>${escapeHtml(a.name)}</strong><small>${escapeHtml(a.type==='hot'?'Hot holding':a.type[0].toUpperCase()+a.type.slice(1))} · target ${a.min} to ${a.max}°C</small></span><span class="reading">${r?`${Number(r.value).toFixed(1)}°C`:'Pending'}</span><span class="row-chevron">›</span></button>`}).join('');$$('[data-temp-asset]').forEach(b=>b.onclick=()=>openTemperatureEntry(Number(b.dataset.tempAsset)));const bar=$('#temperatureCompleteBar');bar.disabled=done!==total;bar.textContent=done===total?'✓ Temperature complete':'Complete all checks first';bar.classList.toggle('ready',done===total);updateManager()}
  function openTemperatureEntry(index){currentIndex=Math.max(0,Math.min(index,state.assets.length-1));const a=state.assets[currentIndex];const r=recordBucket()[a.id];draftValue=r?.value??a.default;draftNote=r?.note||'';renderEntry();showPage('temperature-entry')}
  function renderEntry(){const a=state.assets[currentIndex];const st=statusFor(a,draftValue);$('#entrySessionLabel').textContent=`${session[0].toUpperCase()+session.slice(1)} check`;$('#entryAssetName').textContent=a.name;$('#entryProgress').textContent=`${currentIndex+1} / ${state.assets.length}`;$('#temperatureValue').textContent=`${Number(draftValue).toFixed(1)}°C`;const pill=$('#temperatureStatus');pill.textContent=st.label;pill.className=`status-pill ${st.className}`;
    const wheel=[draftValue+a.step*2,draftValue+a.step,draftValue,draftValue-a.step,draftValue-a.step*2];
    $('#wheelValues').innerHTML=wheel.map((v,i)=>`<button class="wheel-value ${i===2?'active':''}" data-wheel="${v}">${Number(v).toFixed(1)}</button>`).join('');
    $$('[data-wheel]').forEach(b=>b.onclick=()=>{draftValue=Number(b.dataset.wheel);renderEntry()});
    $('#entryProgressDots').innerHTML=state.assets.map((_,i)=>`<span class="${i===currentIndex?'active':''} ${recordBucket()[state.assets[i].id]?'done':''}"></span>`).join('');
    $('#notePreview').hidden=!draftNote;$('#notePreview').textContent=draftNote?`Note: ${draftNote}`:'';$('#previousTemperature').disabled=currentIndex===0}
  function adjustTemperature(direction){const a=state.assets[currentIndex];draftValue=Math.round((draftValue+(direction*a.step))*10)/10;renderEntry()}
  function commitCurrent(andNext=true, correctiveAction=null){const a=state.assets[currentIndex];const now=new Date();recordBucket()[a.id]={value:draftValue,note:draftNote,photo:$('#temperaturePhoto').files.length>0,time:now.toISOString(),correctiveAction};if(correctiveAction){state.issues[todayKey()]??={};state.issues[todayKey()][a.id]={assetId:a.id,session,value:draftValue,action:correctiveAction.action,note:correctiveAction.note||'',createdAt:now.toISOString(),recheckAt:correctiveAction.action==='recheck'?new Date(now.getTime()+15*60000).toISOString():null,status:correctiveAction.action==='recheck'?'waiting':'open'};}save();renderTemperatureList();renderModules('kitchen');toast(`${a.name} saved`);if(andNext&&currentIndex<state.assets.length-1)openTemperatureEntry(currentIndex+1);else if(andNext){showPage('temperature-list');toast('Temperature checks completed')}}
  function saveCurrent(andNext=true){const a=state.assets[currentIndex];const st=statusFor(a,draftValue);if(st.className==='high'){pendingSaveNext=andNext;openActionModal();return}commitCurrent(andNext,null)}
  function openActionModal(){const a=state.assets[currentIndex];selectedAction='';$('#actionNote').value='';$('#actionTemperatureSummary').textContent=`${a.name} · ${Number(draftValue).toFixed(1)}°C · target ${a.min} to ${a.max}°C`;$$('[data-action-choice]').forEach(b=>b.classList.remove('selected'));$('#saveAction').disabled=true;openModal($('#actionModal'))}
  function closeActionModal(){closeModal($('#actionModal'))}

  function renderCleaningList(){syncCleaningIssues();const open=openCleaningTasks(),total=state.cleaningTasks.length,done=total-open.length;$('#cleaningProgressText').textContent=`${done} / ${total}`;$('#cleaningProgressFill').style.width=`${total?done/total*100:100}%`;const renderGroup=(bucket,target)=>{const tasks=open.filter(t=>t.bucket===bucket);$(target).innerHTML=tasks.map(t=>`<button class="cleaning-task-card ${bucket==='overdue'?'is-overdue':''}" data-cleaning-task="${escapeHtml(t.id)}"><span class="progress-circle"></span><span><strong>${escapeHtml(t.title)}</strong><small>${escapeHtml(t.area)} · ${escapeHtml(t.due)}</small></span><em>›</em></button>`).join('');return tasks.length};const today=renderGroup('today','#todayCleaningTasks'),overdue=renderGroup('overdue','#overdueCleaningTasks');$('#todayCleaningCount').textContent=`${today} open`;$('#overdueCleaningCount').textContent=`${overdue} overdue`;$('.overdue-group').hidden=overdue===0;$('.cleaning-group').hidden=today===0;$('#cleaningEmpty').hidden=open.length!==0;$$('[data-cleaning-task]').forEach(b=>b.onclick=()=>openCleaningDetail(b.dataset.cleaningTask));renderModules('kitchen');renderModules('service');updateManager()}
  function openCleaningDetail(id){const task=state.cleaningTasks.find(t=>t.id===id);if(!task)return;currentCleaningId=id;signatureHasInk=false;$('#cleaningDetailPriority').textContent=task.bucket==='overdue'?'Overdue':'To Do Today';$('#cleaningDetailPriority').classList.toggle('danger-text',task.bucket==='overdue');$('#cleaningDetailTitle').textContent=task.title;$('#cleaningDetailArea').textContent=task.area;$('#cleaningDetailInstructions').textContent=task.instructions;$('#cleaningDetailDue').textContent=task.due;$('#cleaningStaff').innerHTML='<option value="">Select staff member</option>'+state.staff.map(x=>`<option>${escapeHtml(x)}</option>`).join('');$('#cleaningStaff').value='';$('#cleaningNote').value='';$('#cleaningPhoto').value='';$('#cleaningPhotoLabel').textContent='Optional';clearSignaturePad();validateCleaning();showPage('cleaning-detail')}
  function validateCleaning(){$('#confirmCleaning').disabled=!($('#cleaningStaff').value&&signatureHasInk)}
  function clearSignaturePad(){const c=$('#signaturePad'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);signatureHasInk=false;validateCleaning()}
  function confirmCleaningTask(){const task=state.cleaningTasks.find(t=>t.id===currentCleaningId);if(!task||!$('#cleaningStaff').value||!signatureHasInk)return;const staff=$('#cleaningStaff').value,now=new Date();cleaningBucket()[task.id]={staff,note:$('#cleaningNote').value.trim(),photo:$('#cleaningPhoto').files.length>0,signature:true,time:now.toISOString()};addAudit('cleaning','confirmed',task.id,{staff,photo:$('#cleaningPhoto').files.length>0,note:$('#cleaningNote').value.trim(),bucket:task.bucket});syncCleaningIssues();save();$('#cleaningSuccessTitle').textContent=task.title;$('#cleaningSuccessMeta').textContent=`Completed by ${staff} · ${now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;$('#cleaningSuccess').hidden=false;setTimeout(()=>{$('#cleaningSuccess').hidden=true;showPage('cleaning-list');renderCleaningList()},650)}

  function updateManager(){syncCleaningIssues();const rec=state.records[todayKey()]?.opening||{};const done=Object.keys(rec).length;const total=state.assets.length;const allIssues=Object.values(state.issues?.[todayKey()]||{}).filter(i=>i.status!=='resolved');const tempIssues=allIssues.filter(i=>i.source!=='cleaning');const cleaningIssues=allIssues.filter(i=>i.source==='cleaning');$('#temperatureSummary').textContent=tempIssues.length?`${tempIssues.length} action${tempIssues.length===1?'':'s'}`:`${done} / ${total}`;const missing=total-done;const attention=missing+allIssues.length;$('#attentionCount').textContent=attention;let rows='';if(cleaningIssues.length){rows+=cleaningIssues.map(issue=>`<button data-open-cleaning-manager><span class="alert-mark">!</span><span><strong>${escapeHtml(issue.title||'Overdue cleaning')}</strong><small>Kitchen · overdue cleaning task</small></span><em>Open</em></button>`).join('')}if(tempIssues.length){rows+=tempIssues.map(issue=>{const a=state.assets.find(x=>x.id===issue.assetId);const due=issue.recheckAt?` · recheck ${new Date(issue.recheckAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:'';return `<button data-open-temp-manager><span class="alert-mark">!</span><span><strong>${escapeHtml(a?.name||'Temperature')} · ${Number(issue.value).toFixed(1)}°C</strong><small>${escapeHtml(issue.action.replace(/-/g,' '))}${due}</small></span><em>Action</em></button>`}).join('')}if(missing){rows+=`<button data-open-temp-manager><span class="alert-mark">!</span><span><strong>Opening temperatures</strong><small>Kitchen · ${missing} check${missing===1?'':'s'} missing</small></span><em>Open</em></button>`}if(!rows)rows=`<button><span class="alert-mark" style="color:var(--green);background:rgba(169,237,121,.12)">✓</span><span><strong>All priority work complete</strong><small>Kitchen · no open issues</small></span><em>Done</em></button>`;$('#managerAttention').innerHTML=rows;const latestAudit=state.auditLog.at(-1);const latestTemp=Object.entries(rec).sort((a,b)=>new Date(b[1].time)-new Date(a[1].time))[0];if(latestAudit&&(!latestTemp||new Date(latestAudit.at)>new Date(latestTemp[1].time))){$('#lastActivityTime').textContent=new Date(latestAudit.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('#lastActivityText').textContent=`Kitchen · ${latestAudit.module==='cleaning'?'Cleaning':'Audit'}`}else if(latestTemp){const a=state.assets.find(x=>x.id===latestTemp[0]);$('#lastActivityTime').textContent=new Date(latestTemp[1].time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('#lastActivityText').textContent=`Kitchen · ${a?.name||'Temperature'}`}$$('[data-open-temp-manager]').forEach(b=>b.onclick=()=>{session='opening';renderTemperatureList();showPage('temperature-list')});$$('[data-open-cleaning-manager]').forEach(b=>b.onclick=()=>{renderCleaningList();showPage('cleaning-list')})}
  function openModal(m){m.classList.add('open')} function closeModal(m){m.classList.remove('open')} function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1600)}

  $$('[data-target]').forEach(b=>b.onclick=()=>showPage(b.dataset.target));$$('[data-go-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.goPage));$('[data-department-home]').onclick=()=>showPage(mode);$('#modeChip').onclick=e=>{e.stopPropagation();$('#modeMenu').classList.toggle('open')};$$('[data-switch-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.switchMode));document.onclick=e=>{if(!$('#modeMenu').contains(e.target)&&e.target!==$('#modeChip'))$('#modeMenu').classList.remove('open')};
  $$('[data-close-modal]').forEach(b=>b.onclick=()=>closeModal($('#moduleModal')));$$('[data-session]').forEach(b=>b.onclick=()=>{session=b.dataset.session;$$('[data-session]').forEach(x=>x.classList.toggle('active',x===b));renderTemperatureList()});$$('[data-temp-back]').forEach(b=>b.onclick=()=>showPage(mode==='manager'?'kitchen':mode));$('[data-temp-list]').onclick=()=>{saveCurrent(false);showPage('temperature-list')};$$('[data-temp-adjust]').forEach(b=>b.onclick=()=>adjustTemperature(Number(b.dataset.tempAdjust)));$('#previousTemperature').onclick=()=>{saveCurrent(false);openTemperatureEntry(currentIndex-1)};$('#saveNextTemperature').onclick=()=>saveCurrent(true);
  $('#addNoteButton').onclick=()=>{$('#temperatureNote').value=draftNote;openModal($('#noteModal'))};$$('[data-close-note]').forEach(b=>b.onclick=()=>closeModal($('#noteModal')));$('#saveNote').onclick=()=>{draftNote=$('#temperatureNote').value.trim();closeModal($('#noteModal'));renderEntry();toast('Note saved')};
  const swipe=$('#temperatureSwipeArea');swipe.addEventListener('touchstart',e=>touchStartX=e.changedTouches[0].screenX,{passive:true});swipe.addEventListener('touchend',e=>{const dx=e.changedTouches[0].screenX-touchStartX;if(Math.abs(dx)<60)return;if(dx<0)saveCurrent(true);else if(currentIndex>0){saveCurrent(false);openTemperatureEntry(currentIndex-1)}},{passive:true});
  const wheel=$('#temperatureWheel');
  wheel.addEventListener('touchstart',e=>{wheelTouchStartY=e.touches[0].clientY;wheelLastY=wheelTouchStartY;wheelAccumulator=0},{passive:true});
  wheel.addEventListener('touchmove',e=>{const y=e.touches[0].clientY;const dy=wheelLastY-y;wheelLastY=y;wheelAccumulator+=dy;const a=state.assets[currentIndex];const pixelsPerStep=8;while(Math.abs(wheelAccumulator)>=pixelsPerStep){const direction=wheelAccumulator>0?1:-1;draftValue=Math.round((draftValue+direction*a.step)*10)/10;wheelAccumulator-=direction*pixelsPerStep;}renderEntry();},{passive:true});
  wheel.addEventListener('touchend',()=>{wheelAccumulator=0},{passive:true});
  $$('[data-action-choice]').forEach(b=>b.onclick=()=>{selectedAction=b.dataset.actionChoice;$$('[data-action-choice]').forEach(x=>x.classList.toggle('selected',x===b));$('#saveAction').disabled=false});
  $('#cancelAction').onclick=closeActionModal;
  $('#saveAction').onclick=()=>{if(!selectedAction)return;const action={action:selectedAction,note:$('#actionNote').value.trim()};closeActionModal();commitCurrent(pendingSaveNext,action)};
  $$('[data-cleaning-back]').forEach(b=>b.onclick=()=>showPage(mode==='manager'?'kitchen':mode));$$('[data-cleaning-list]').forEach(b=>b.onclick=()=>{renderCleaningList();showPage('cleaning-list')});$('#cleaningStaff').onchange=validateCleaning;$('#cleaningPhoto').onchange=()=>{$('#cleaningPhotoLabel').textContent=$('#cleaningPhoto').files.length?'Photo added':'Optional'};$('#clearSignature').onclick=clearSignaturePad;$('#confirmCleaning').onclick=confirmCleaningTask;
  const signature=$('#signaturePad'),sigCtx=signature.getContext('2d');sigCtx.lineWidth=4;sigCtx.lineCap='round';sigCtx.strokeStyle='#f6f8fa';const signaturePoint=e=>{const r=signature.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*(signature.width/r.width),y:(p.clientY-r.top)*(signature.height/r.height)}};const signatureStart=e=>{e.preventDefault();signatureDrawing=true;const p=signaturePoint(e);sigCtx.beginPath();sigCtx.moveTo(p.x,p.y)};const signatureMove=e=>{if(!signatureDrawing)return;e.preventDefault();const p=signaturePoint(e);sigCtx.lineTo(p.x,p.y);sigCtx.stroke();signatureHasInk=true;validateCleaning()};const signatureEnd=e=>{if(e)e.preventDefault();signatureDrawing=false};signature.addEventListener('pointerdown',signatureStart);signature.addEventListener('pointermove',signatureMove);window.addEventListener('pointerup',signatureEnd);signature.addEventListener('touchstart',signatureStart,{passive:false});signature.addEventListener('touchmove',signatureMove,{passive:false});signature.addEventListener('touchend',signatureEnd,{passive:false});
  $$('[data-setup-tab]').forEach(b=>b.onclick=()=>{$$('[data-setup-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-setup-content]').forEach(x=>x.classList.toggle('active',x.dataset.setupContent===b.dataset.setupTab))});
  $('#addTemperatureAsset').onclick=()=>{const id=`asset-${Date.now()}`;state.assets.push({id,name:'New Fridge',type:'fridge',min:0,max:5,step:.1,default:4});save();renderTemperatureEditor();renderTemperatureList();renderModules('kitchen');toast('Equipment added')};
  $('#resetSetup').onclick=()=>{state=clone(defaults);save();renderAll();toast('Defaults restored')};$('#addCustomModule').onclick=()=>{const name=prompt('Module name');if(!name?.trim())return;const dep=(prompt('Kitchen or Service?','Kitchen')||'').toLowerCase();if(!['kitchen','service'].includes(dep))return toast('Choose Kitchen or Service');state.modules[dep].push({id:`custom-${Date.now()}`,name:name.trim(),symbol:'+',description:'Custom operational module',enabled:true,status:'Ready'});save();renderAll();toast('Module added')};
  function renderAll(){syncCleaningIssues();renderModules('kitchen');renderModules('service');renderEditors();renderTemperatureEditor();renderTemperatureList();updateManager()}
  $('#todayLabel').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',day:'numeric',month:'long'}).format(new Date());renderAll();setMode(mode);
})();
